### PR TITLE
Pt br

### PR DESCRIPTION
**Pull request by FKrauss**
I translated the website pages to Brazilian portuguese.

**Important** it is missing a small logo for telgram. I added the twitter one for now, but we just need to change the logo `src`

Apart from that all pages of the website are localized to Brazil, language and currencies too (Brazilian reais were included in addition to the existing fiat currency examples)

-----

btw, had a little mess with commits there. Noob here =)

### CODE REVIEW

**Comment by huey735** [comment]
Hi @FKrauss why didn't you go the Transifex route?

**Comment by FKrauss** [comment]
Because I understood that the website didn't work well with Transifex. Plus because I wanted to change a link to the local telegram account I had to go Github.

was I wrong?

**Comment by wiz** [comment]
First you need to translate the strings on Transifex, like everybody else, then you take the output file from transifex and use those translations as a starting point to localize the website for your locale

**Comment by FKrauss** [comment]
man! what a pleb! 

sorry about that. I'll make things consistent with Transifex then

**Comment by wiz** [comment]
Yeah it's cool, I don't think is this documented anywhere, but the point of using transifex is so we can collaborate together, so it's fine if you do in the opposite order heh

**Comment by FKrauss** [comment]
but by doing it backwards did I break the "bridge" or next time we can simply take transifex and go crazy on it?

**Comment by wiz** [comment]
There is no bridge so it's totally fine to do it in the opposite order if you're doing 100% of everything by yourself 😅

**Comment by erciccione** [comment]
I think would be better to wait until the new multilanguage website is ready before adding new languages. Most of the files changed or added in this PR will be removed and adding more translations now would make the review of the new system much harder.

**Comment by wiz** [comment]
@FKrauss did you test this before submitting the PR? I just took a look but it seems totally broken? https://deploy-preview-254--bisq-website.netlify.com/pt-br/

**Comment by m52go** [comment]
@FKrauss first PR! Some notes:

- please make sure your git commit messages follow the [7 rules here](https://github.com/bisq-network/style/issues/9#issue-319178416)
  - it may seem nit-picky but helps keep commit history clear, consistent, and professional
- please test changes before making a pull request (let us know if you need help setting up a local environment)
- please use the [WIP] prefix for pull requests that aren't ready to be merged immediately
- [critical] translations should use the transifex workflow (will discuss soon)

None of the major pages work correctly, and it seems this PR will need some reworking (both in terms of code and workflow) before it can be merged, so I will close it for now.

**Comment by m52go** [comment]
NACK

**Pull request closed without merging**
