### PR TITLE
Change order of downloads redirects

### PR DESCRIPTION
**Pull request by devinbileck**
Fixes https://github.com/bisq-network/bisq-website/issues/132

### CODE REVIEW

**Comment by ripcurlx** [comment]
The urls are still incorrect: https://github.com/bisq-network/bisq/releases/download/archive/v0.9.4.zip --> not found.
Should be: https://github.com/bisq-network/bisq/archive/v0.9.4.zip

**Comment by ripcurlx** [comment]
The source code links have a different path than the other download links.

**Review by ripcurlx — DISMISSED** [review]
NACK - see my comments above

**Comment by devinbileck** [comment]
Hmm.. I used this link to verify that it works: https://deploy-preview-133--bisq-website.netlify.com/downloads/archive/v0.9.4.zip

**Comment by ripcurlx** [comment]
> Hmm.. I used this link to verify that it works: https://deploy-preview-133--bisq-website.netlify.com/downloads/archive/v0.9.4.zip

Ah sure - I just went to the download section an there it uses the final domain and not the deploy preview domain for the redirect.

**Comment by ripcurlx** [comment]
utACK

**Pull request merged**
