### PR TITLE
Add headers to improve security

### PR DESCRIPTION
**Pull request by ripcurlx**
Based on feedback from https://observatory.mozilla.org/analyze/bisq.network.

### CODE REVIEW

**Comment by ripcurlx** [comment]
It is configured as described in https://www.netlify.com/docs/headers-and-basic-auth/. But I don't see it in the test build.

**Comment by ripcurlx** [comment]
I do see the correct headers on sub sites (e.g. vision), but it should be actually also configured for the root as well.

**Comment by ripcurlx** [comment]
To use https://infosec.mozilla.org/guidelines/web_security#content-security-policy is a little bit more effort as I would need to check for all in-line scripts and do lots of testing not to break anything. Will be a next step.

**Comment by m52go** [comment]
ACK

**Pull request merged**
