### PR TITLE
Add Slovak language

### PR DESCRIPTION
**Pull request by Alfavio**
I translated the Bisq website to the Slovak language. Some characters were broken, so I also updated the font _[(source)](https://github.com/IBM/plex)_. 

Also, I noticed, that in FAQ is inconsistent information about multisig addresses. 

- In _["Is Bisq safe and open-source?" ](https://bisq.network/faq/#safe-open-source)_ is mentioned: _"All bitcoins traded with Bisq are secured in a **2-of-2** multisignature address."_
-  In [_"What is a Bitcoin ‘multisignature address’?"_](https://bisq.network/faq/#whats-multisig) is mentioned: _"Bisq uses **2-of-3** multisig addresses."_

I translated it as it is in the current English version.

### CODE REVIEW

**Comment by m52go** [comment]
@Alfavio appreciate the initiative!

As you might have noticed from the code base, site translations are a bit of a mess right now. This is why adding new ones is officially on hold right now.
* Transifex is not correctly set up
* source files in this repository are rather inefficient

I'll work on fixing these issues in the next week or so.

More importantly, technical issues aside, do you have any thoughts on the following:
1. We've had issues with contributors doing a whole new translation and then disappearing, making maintaining new languages all but impossible. I recall seeing your around here a couple times, but can we rely that you'll be around to update the Slovak translation when needed?
2. Do you think there are a lot of Slovak-speaking Bisq users? Budget for maintaining translations is very low, so we need to make sure any new translations are worthwhile. I see you requested for the language also be added to the desktop software. Maybe it's better to do a small chunk of the work first and see how much it's used before doing the whole thing? I know from experience with Paralelni Polis that there are a good number of Czechs and Slovaks interested in Bisq, but I'm not sure if it's important enough for a translation (i.e., most seem ok with English?).

@mwithm feel free to chime in if you have any thoughts here.

> Also, I noticed, that in FAQ is inconsistent information about multisig addresses.

Unbelievable. I can't believe such a major error was not discovered yet. Thank you! [It's fixed now](https://github.com/bisq-network/bisq-website/compare/792e25f9784e...b716accb427b).

**Comment by MwithM** [comment]
Thanks for your initiative @Alfavio the main issue we're facing with translations is that as the project grows, there's more and more things to translate and there's no budget to maintain it. Also, people start a good job but forget to keep it up to date.
We're working to get a simplified set of wiki articles and parts of the web page so we can keep a track and keep it into budget, so we can open translation to more languages.

I found the FAQ multisig addresses error when transcribing this wiki article: https://bisq.wiki/Help:FAQ#Is_Bisq_safe_and_opensource.3F but forgot to report it as I thought that website docs were being abandoned.
BTW, the article for FAQ is a ghost page that I can't even find at https://bisq.wiki/Special:AllPages

**Comment by Alfavio** [comment]
@m52go 
> We've had issues with contributors doing a whole new translation and then disappearing, making maintaining new languages all but impossible. I recall seeing your around here a couple times, but can we rely that you'll be around to update the Slovak translation when needed?

Yes, if I will have time, I can update the Slovak translation, but I can't give a promise. 

> Do you think there are a lot of Slovak-speaking Bisq users? Budget for maintaining translations is very low, so we need to make sure any new translations are worthwhile. I see you requested for the language also be added to the desktop software. Maybe it's better to do a small chunk of the work first and see how much it's used before doing the whole thing? I know from experience with Paralelni Polis that there are a good number of Czechs and Slovaks interested in Bisq, but I'm not sure if it's important enough for a translation (i.e., most seem ok with English?).

I don't know. A Slovak and Czech crypto community is very big, maybe one of the biggest, but I don't know have many there are Slovak-speaking Bisq users. I think the majority of Slovak-speaking users have some knowledge of the English language, but I don't know at what level.

**Comment by m52go** [comment]
I'll revisit this when I update the underlying website translation workflow this week.

**Comment by m52go** [comment]
Closing this as stalled. 

It's stalled because of me, not Alfavio, who graciously offered this contribution to begin with. But as mentioned above, translations were not implemented very well to start and there are very little resources to fix and maintain them.

With that said, I have made a lot of progress in fixing the status quo over the past several months (e.g. reducing the text footprint of the site, deleting unnecessary pages, moving items to the wiki, etc), but there is still more work to do.

To prevent this kind of stalled/unapproved translations PR from happening again, I added [a note to the README of this repository a while ago](https://github.com/bisq-network/bisq-website/commit/4b52fa9e80e7fc5f3ab2aefe100c417bfac079b6#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) late last year. Sorry Alfavio.

**Pull request closed without merging**
