### PR TITLE
Add Japanese localizations

### PR DESCRIPTION
**Pull request by wiz**

### CODE REVIEW

**Comment by huey735** [comment]
@wiz when running the website locally I get this error:
```
[2019-09-06 12:15:47] ERROR `/images/apple-touch-icon.png' not found.
[2019-09-06 12:15:52] ERROR `/de/images/community/github.svg' not found.
[2019-09-06 12:15:52] ERROR `/de/images/community/twitter.svg' not found.
[2019-09-06 12:15:52] ERROR `/de/images/community/youtube.svg' not found.
[2019-09-06 12:15:52] ERROR `/de/images/community/slack.svg' not found.
[2019-09-06 12:15:52] ERROR `/de/images/community/forum.svg' not found.
[2019-09-06 12:15:52] ERROR `/de/images/community/mailinglist.svg' not found.
[2019-09-06 12:15:52] ERROR `/de/images/community/irc.svg' not found.
[2019-09-06 12:15:52] ERROR `/de/images/community/reddit.svg' not found.
```

So I changed the image sources links for the community page to go a level higher:
img src="../images/community/github.svg" alt="github"
img src="../../images/community/github.svg" alt="github"

You don't seem to have that problem. What am I missing?

**Comment by wiz** [comment]
@huey735 the issue you've identified is not related to this PR, but I've submitted PR #235 to fix it

**Comment by wiz** [comment]
@m52go okay this PR is ready for review, preview at https://deploy-preview-229--bisq-website.netlify.com/ja/

Only 70% of strings are translated so far, but we want to ship this to prepare for the upcoming v1.1.6 release. We will submit remaining 30% of strings in another PR soon.

**Comment by huey735** [comment]
@wiz you need to be careful with hyperlinks and make sure if there's space before and after. For example: https://www.transifex.com/bisq/bisq-website/translate/#ja/strings/174374865?q=text%3AGithub.

**Comment by wiz** [comment]
@huey735 The Japanese language doesn't use spaces.

**Comment by huey735** [comment]
@wiz Oh. It's something that has happened with most translations and some strings did look a little snuggled but never mind it them.

**Comment by m52go** [comment]
ACK

**Comment by wiz** [comment]
@huey735 no worries, yeah in most languages this would be a mistake, but in this case the spaces were intentionally removed.

thanks everyone for reviewing and merging! 🎉

**Pull request merged**
