### PR TITLE
Refactoring in preparation for the new localization system

### PR DESCRIPTION
**Pull request by erciccione**
Refactored base of the repo (so, only the English section) in preparation for the new localization system. This is part of #244.

- Renamed `strings_en.yml` to `en.yml`. For consistency with the other languages and to get it ready fot the multilingual plugin.
- Rename index.md to index.html and add variables (strings will be pulled from `en.yml`)
- ~~Remove `_includes/homepage_content.html` and correctly use index.html instead~~
- `faq.html`, `stats.html`, `markets.html` and `downloads.html` now correctly pull strings from `_data/en.yml`

### CODE REVIEW

**Comment by m52go** [comment]
@erciccione great to see this moving forward. Content looks good to me.

The front page has an issue with the background, possibly related with the change in the default template.

See PR on the left and master on the right:

Screenshot from 2019-09-23 09-28-40

Also different spacing on mobile (probably related):

Screenshot from 2019-09-23 09-35-24

Also, I appreciate your detailed commit messages, but please follow [these 7 rules](https://github.com/bisq-network/style/issues/9#issue-319178416). In particular, keep the subject line under 50 characters and the first word a verb in imperative form.

**Comment by erciccione** [comment]
Nice catch @m52go, apparently the layout get messed up if we pull index.html instead of using a snippet in _include. Still trying to figure out how to fix without touching the layout too much, but i don't want to spend too much time on it. If i can't figure it out quick i will just revert back to pulling `homepage_content.html` for now. The way languages are picked will be changed anyway.

> please follow these 7 rules.

Sorry about that, will fix with the next push.

**Comment by erciccione** [comment]
I put back `homepage_content.html`, which is basically a copy of `index.html` (still unused and only renamed, for now) and will be removed with the new system,  and changed the text of the commit. Everything should be working properly.

**Comment by m52go** [comment]
ACK

**Pull request merged**
