### PR TITLE
Add search

### PR DESCRIPTION
**Pull request by stevavoliajvar**
As per [this](https://github.com/bisq-network/bisq-website/pull/411#event-4204161962) I made changes.

It now: 
 + opens in new tab
 + no shadow 
 + has seperate button
 + has better spacing

@m52go

### CODE REVIEW

**Comment by stevavoliajvar** [comment]
Is there any update on this ? Will it be merged ?

**Comment by m52go** [comment]
@stevavoliajvar sorry for the delay -- I had pinged our designer off-line a while ago, but then it slipped through the cracks. There some minor improvements I'd like to make, which I'll push in a few hours, and then merge it. It's much improved overall :+1:

**Comment by m52go** [comment]
Updates are now implemented...will merge soon @stevavoliajvar unless you have any further comments.

**Light mode desktop**

Screenshot from 2021-03-16 12-39-22

**Dark mode desktop**

Screenshot from 2021-03-16 12-39-31

**Mobile**

Screenshot from 2021-03-16 12-39-44

**Comment by stevavoliajvar** [comment]
Cool, glad I helped :D

**Pull request merged**
