### PR TITLE
Make fee explanation clearer

### PR DESCRIPTION
**Pull request by m52go**
To address @ManfredKarrer's proposal here:
https://github.com/bisq-network/proposals/issues/31

[Removed screenshot since there's now a Netlify preview]

### CODE REVIEW

**Review by cbeams — APPROVED** [review]
ACK. This is such a great improvement. I've added one touch-up commit that you'll see.

@ManfredKarrer, before merging this, I'd like to have you review it too for accuracy.

**Comment by cbeams** [comment]
I've added a couple additional clarifying commits. Manfred, for convenience in your review, please see the current rendering of all of @m52go and my changes at https://deploy-preview-73--bisq-website.netlify.com/faq/#6.

**Review by ManfredKarrer — APPROVED** [review]
ACK
Thanks a lot!!! Now it is much more clear!

**Comment by ManfredKarrer** [comment]
Thanks @cbeams for the preview. Easier to review!

**Comment by cbeams** [comment]
> Thanks @cbeams for the preview. Easier to review!

Sure. Note that these previews are available for all PRs against `bisq-website` and `bisq-docs`, and they're regenerated every time a commit is pushed against the PR branch. You can find the links in the Slack notifications in their respective channels, and you can find the links right here in the PR under the 'Checks' section:

image

**Pull request merged**
