### PR TITLE
Update english site description

### PR DESCRIPTION
**Pull request by m52go**
To something more consistent with wording used in other places, [per this comment](https://github.com/bisq-network/bisq-website/pull/280#discussion_r351497689).

### CODE REVIEW

**Review by RiccardoMasutti — APPROVED** [review]

**Comment by RiccardoMasutti** [comment]
Why not add a translated description for each language?

**Comment by m52go** [comment]
Yes that would be best. There are too many English updates that haven't been translated to other languages yet. It's a bad (and undocumented) workflow. Had a call about it today, should be making progress on it next week.

**Comment by RiccardoMasutti** [comment]
> Yes that would be best. There are too many English updates that haven't been translated to other languages yet. It's a bad (and undocumented) workflow. Had a call about it today, should be making progress on it next week.

Are there any strings on Transifex?

**Comment by m52go** [comment]
There are, but they probably aren't updated. Someone else was in charge of making sure they were updated, but they aren't around anymore. 

I assume just the YML files just need to be uploaded there, but I need to confirm. Do you have experience with Transifex?

**Comment by RiccardoMasutti** [comment]
> There are, but they probably aren't updated. Someone else was in charge of making sure they were updated, but they aren't around anymore.
> 
> I assume just the YML files just need to be uploaded there, but I need to confirm. Do you have experience with Transifex?

Yes I have

**Pull request closed without merging**
