### PR TITLE
Replace slack with keybase throughout site

### PR DESCRIPTION
**Pull request by m52go**
To fulfill https://github.com/bisq-network/proposals/issues/144.

Notes:
* all instances of the string "slack" should be gone from the website except (a) blog post bodies and (b) the `/stats` page.
  * didn't want to edit other peoples' published content...all links will lead to a new `/slack-invite` page with a Keybase link anyway.
  * stats page will replace Slack numbers with Keybase numbers in the update for November, which will come next week after the month ends.
* there's now a simple page at `/slack-invite` to tell anyone who clicks the old Slack invite link about Keybase...I just removed the redirect, so anyone going to `https://bisq.network/slack-invite` will see this page instead.
* `images/community/slack.svg` remains...I don't believe the git repository will reduce in size if it's removed anyway.

### CODE REVIEW

**Review by RiccardoMasutti — APPROVED** [review]

**Review by wiz — APPROVED** [review]

**Comment by wiz** [comment]
test

**Comment by wiz** [comment]
test

**Comment by m52go** [comment]
test

**Comment by m52go** [comment]
test again

**Pull request merged**
