### PR TITLE
Implement the ability to display localized app screenshots

### PR DESCRIPTION
**Pull request by wiz**
Implement displaying localized app screenshots on homepage, just replace the screenshots in /<lang>/images/bisq_screen0.png and bisq_screen1.png with localized ones

### CODE REVIEW

**Comment by huey735** [comment]
@wiz @m52go it may be required to change the name of the image files for each language as it was done for the Dao images. https://github.com/bisq-network/bisq-website/pull/201

**Comment by m52go** [comment]
@huey735 not needed any more. wiz figured out why that was happening and fixed it with #232, such that images now work as expected (example: see https://deploy-preview-230--bisq-website.netlify.com/es/).

**Comment by m52go** [comment]
This PR provides implements the plumbing for localized screenshots, so I will merge it, and the actual new pictures can be added in a new PR.

**Comment by m52go** [comment]
ACK

**Pull request merged**
