### PR TITLE
Update fee structure on faq page

### PR DESCRIPTION
**Pull request by m52go**
To address #246. We discussed making a new web page for fees, but that is probably best left for separate PR.

### CODE REVIEW

**Comment by m52go** [comment]
@ifarnung feel free to take a look at the preview too...let me know if you have any thoughts:

https://deploy-preview-248--bisq-website.netlify.com/faq/#cost-to-trade

**Review by erciccione — CHANGES_REQUESTED** [review]
The changes to the faq page need to be added to the other languages as well.

**Comment by m52go** [comment]
@erciccione thanks. I can only write in English, so I added the update to `strings_en.yml` and marked the other FAQ pages as outdated.

**Comment by erciccione** [comment]
@m52go Wouldn't be better to have the english text in all the localized `faq.html` files as well? Otherwise i'm afraid we could lose these strings for the other languages (this problem will be solved by #244 tho, since a good amount of these duplicated files will be deleted)

**Comment by m52go** [comment]
@erciccione how would they get lost? I thought the strings_en.yml file was the base file used for translating into other languages.

In any case, yes, seems like your refactoring is sorely needed. Something isn't right with this setup.

**Comment by erciccione** [comment]
> I thought the strings_en.yml file was the base file used for translating into other languages.

Nope, that will be the situation once #244 will be implemented. Right now strings are split between `strings_en.yml` and html files and everytime something is changed the language files must be adapted. In this case the `faq.html` page of every language must be adapted. A further complication is that the strings of the language files are not in `[LANG]/faq.html` (like it is for the english strings), but in `[LANG].yml`. So, according to the current workflow the english strings are in `faq.html`, but the translated strings are variables in `[LANG]/faq.html` that will be pulled from `_data/[LANG].yml`.

Yes, it's a mess, that's why i agree #244 is badly needed :)

**Comment by erciccione** [comment]
> Something isn't right with this setup

I think it was a mistake made during the conversion to the website to make it able to host translations. All strings should have been added to the `strings_en.yml`, but for some reasons most of them were left in their original file, which result in a very messed up structure and workflow.

**Comment by m52go** [comment]
@erciccione I agree it's not ideal to have an answer that's not thorough (current answer with `outdated_translations` flag), but isn't it worse to have a thorough answer that no one can understand (new answer in English)?

@huey735 side note / curiosity: the [trading fees question on the FAQs page](https://bisq.network/faq/#cost-to-trade) doesn't seem to mention BSQ on any of the non-English pages. I wonder how that happened? BSQ has been a part of the English version for months now, presumably before any website translations started.

**Comment by huey735** [comment]
@m52go I've just noticed that it's missing from `strings_en.yml` so it didn't make to Transifex, I'll get to it.

**Comment by huey735** [comment]
@erciccione the strings I'm referencing are related to this PR. I'd be creating a new PR to update the strings_en.yml file.

**Comment by m52go** [comment]
@erciccione @huey735 I've rebased this PR now that #256 is merged. 

What's the deal with this PR? Can it be merged?

I know the way it handles non-English languages isn't ideal, but that's not the point of this PR, and it's not a valid reason to hold it up. It uses the conventions of the current set-up, which is the best it can do.

**Comment by erciccione** [comment]
@m52go I'm fine with this getting merged, it's not a big deal to adapt it to the new system.

**Pull request merged**
