### PR TITLE
Update ruby to v2.6.2

### PR DESCRIPTION
**Pull request by m52go**
Ruby 2.4 reaches EOL in March 2020.

It seems like Ruby does annual deprecations for their major versions, so [2.6 should be good through March 2022](https://www.ruby-lang.org/en/downloads/branches/). This PR moves to 2.6.2, which is the only version of Ruby 2.6 that Netlify seems to fully support at the moment.

### CODE REVIEW

**Comment by m52go** [comment]
It seems Netlify is failing to build...will need to solve before this can be merged.

https://deploy-preview-330--bisq-website.netlify.com/

**Comment by m52go** [comment]
Turns out 2.6.5 isn't fully supported by Netlify...2.6.2 is the only one that works.

**Review by RiccardoMasutti — APPROVED** [review]
ACK

**Comment by m52go** [comment]
@ripcurlx FYI, just want to make sure you see this update, so you're not blindsided with an issue next time you update the site for a new release.

**Pull request merged**
