### PR TITLE
Only display actively traded markets on the bisq.network/markets page

### PR DESCRIPTION
**Pull request by wiz**
Adds a script to update list of Bisq markets from the active markets API, and updates the list using that script.

For more information see https://github.com/mempool/mempool/pull/189, https://github.com/bisq-network/bisq/pull/4831, and https://github.com/bisq-network/bisq/issues/4826

### CODE REVIEW

**Comment by wiz** [comment]
Preview at https://deploy-preview-407--bisq-website.netlify.app/markets/

**Comment by m52go** [comment]
Thanks, looks good to me and script seemed to run well. 

Would you say this is something that should be run every so often, maybe every 6 months?

**Comment by wiz** [comment]
Yeah or whenever something new is added

**Comment by m52go** [comment]
ACK

**Pull request merged**
