### PR TITLE
Add Farsi translations

### PR DESCRIPTION
**Pull request by huey735**
@erciccione I messed up the previous PR trying to rebase and squash the commits so I created theis new one.

### CODE REVIEW

**Review by erciccione — COMMENTED** [review]
I see you removed a lot of newlines. That's generally a good thing but in this case it's unrelated to the subject of the PR and spams a lot of unrelated diffs. Next time please make unrelated changes in a new commit or new PR :).

Beside, as i suggested in #254  i think would be better to not add new languages until the new multilingual system will be implemented (will be ready for/before the end of this week).

**Comment by m52go** [comment]
@huey735 looks like the stats page isn't working? I see blank graphs [on the preview](https://deploy-preview-255--bisq-website.netlify.com/fa/stats/).

@erciccione like we discussed on Slack, ongoing work will continue during refactoring...will just avoid significant changes. I don't think adding new languages significant, since they use existing conventions and structures.

**Comment by erciccione** [comment]
@m52go Adding a new language is significant if at the same time we are changing the way languages work IMHO.

Anyway, i understand you want to merge opened PR first, so i will just put my work on hold until that's done, because it would take much longer to rebase my changes than just wait and start with this as a base.

Just please, no new PRs with new languages, or each time i will have to rebase stuff that will have to remove, or completely change, right after. Which is a waste of time.

**Comment by huey735** [comment]
@m52go I fixed the issue. It was because I had started working on the Stats page before its re-factorization.

**Comment by huey735** [comment]
@erciccione I have some strings on strings_en.yml to update related to https://github.com/bisq-network/bisq-website/pull/248#issuecomment-533969897. Can I go ahead and do so or does it conflict with your current work?

**Comment by erciccione** [comment]
@huey735 If you still have to work on it, would be better to use #256 as a base for your changes, so that none of us two will have to rebase and the new strings will be ready for the new system :)

**Comment by m52go** [comment]
@huey735 if this is close to be ready for merging, let's continue with it. I don't see why there would be any conflicts with 256, and if there are, they should be minor (also this PR came first).

With that said, do you have any languages in progress after Farsi? Perhaps we could put a short hold on new languages if it makes a big enough difference for erciccione.

> I have some strings on strings_en.yml to update related to #248 (comment). Can I go ahead and do so or does it conflict with your current work?

Would that be related to this PR?

**Comment by huey735** [comment]
@m52go 
> With that said, do you have any languages in progress after Farsi?

No

> Would that be related to this PR?

Not necessarily, I'd just be updating strings_en.yml with the current text on the website. I was just making sure not to step on @erciccione's ongoing work.

**Comment by m52go** [comment]
> Not necessarily, I'd just be updating strings_en.yml with the current text on the website.

Okay cool, let's leave that out of this PR.

Who did this translation? Might be good to have them take a look to make sure it's good...my ability to review this is limited, particularly because of the right-to-left direction. I applied `direction: rtl;` to some strings...some reversed and some didn't, so I think it would be best to have a native speaker confirm everything's good.

It seems emojis have an issue showing with RTL text on Chromium...possible bug? Would be great if we could find a workaround. 

The flag is correct in source code and shows in Firefox. 

Screenshot from 2019-09-23 08-30-15

**Comment by huey735** [comment]
> Okay cool, let's leave that out of this PR.

No, I would be creating w new PR specifically to update the strings.

@Blockchainsmoker did most of it, I'll reach out to them. I've tested here on Firefox and Brave(Chrome) and I had no issue.

**Comment by BLOCKCHAINSMOKER** [comment]
@m52go  @huey735 @erciccione Hi everyone and thanks for the patience. It looks like the RTL did not take on all pages
Screen Shot 2019-09-24 at 11 06 38 AM

https://5d8885d38dc38f0007f6f97d--bisq-website.netlify.com/fa/faq/

These are taken using Safari, firefox and chrome browsers.They are all using RTL instead of LTR.

**Comment by BLOCKCHAINSMOKER** [comment]
I think it would be best to fix this issue with the translations first. Because there may be some other issue that are flowing from this. RTL/LTR Issue
For instance when we include an english word such as "BSQ" with the farsi translation the whole string can get scrambled with the english word that should be last coming in first.

**Comment by BLOCKCHAINSMOKER** [comment]
The other problems that might be flowing from the left to right issue can be seen in the two below screen shots. 
Screen Shot 2019-09-24 at 10 59 59 AM
Screen Shot 2019-09-24 at 11 00 46 AM

The screen shot taken from the website is incorrect but the screenshot taken from transifex is correct. The website is incorrect using firefox, safari and chrome.

**Comment by huey735** [comment]
@BLOCKCHAINSMOKER are these issues also present on Firefox?

**Comment by BLOCKCHAINSMOKER** [comment]
You can see that the words in the website version are scrambled. This only occurs when we use english mixed with farsi. 

Perhaps this will be corrected once the LTR is changed to RTL

**Comment by BLOCKCHAINSMOKER** [comment]
@huey735 Firefox corrects only one issue that I have found so far. 

Screen Shot 2019-09-24 at 10 58 59 AM

These parenthesis line up correctly on firefox. 

Screen Shot 2019-09-24 at 3 05 08 PM

But this is the only item I have found so far that is corrected on firefox.

**Comment by m52go** [comment]
I don't see the `direction: rtl;` property being used in CSS anywhere; might that help?

@huey735 would it be fair to put this translation on hold for now so @erciccione can forge onward with the site refactor? It seems issues might take some time to fix (correct me if I'm wrong).

**Comment by huey735** [comment]
@m52go yes the refactoring should gain priority.
Also, @erciccione in your work in translation/localization have you come across people who could help with RTL languages?

**Comment by erciccione** [comment]
@huey735 I'm afraid no. The contributor who added Arabic to getmonero.org was fine with leaving left-to-right, so we ended up keeping it that way.

**Comment by m52go** [comment]
I'm going to close this as @huey735 has been away/unresponsive for a couple months now, and there isn't anyone to properly review this at the moment either.

**Comment by BLOCKCHAINSMOKER** [comment]
> I'm going to close this as @huey735 has been away/unresponsive for a couple months now, and there isn't anyone to properly review this at the moment either.


Can I reopen this and actually add the farsi translations? I have been trying to get this done for 6 months but @huey735 would respond to me or let me help.

**Pull request closed without merging**
