### PR TITLE
[Proposal] Translate Bisq software images in the homepage #207

### PR DESCRIPTION
**Pull request by gilsanjuan**
I worked  14 .svg images from Bisq software, 7 images of Offer book screen ( bisq_screen0), and 7 images of Trades( bisq_screen1). Included EN, ES, DE, FR, PT, JP, CN translations

 I optimized bisq_screen0 to 59 KB, and bisq_screen2 to 38 KB.

At the end, I changed png image extension to svg for bisq_screen0 and bisq_screen1 on index.html, _includes/homepage_content.html and _includes/homepage_content_tr.html

### CODE REVIEW

**Comment by m52go** [comment]
@gilsanjuan, thanks for finally taking care of this!

One nit: could you please un-bold the BTC price? Looks like a heavy font in all screenshots.

PR:

Screenshot from 2019-11-05 11-04-34

Current:

Screenshot from 2019-11-05 11-04-42

**Comment by gilsanjuan** [comment]
@m52go done

> @gilsanjuan, thanks for finally taking care of this!
> 
> One nit: could you please un-bold the BTC price? Looks like a heavy font in all screenshots.
> 
> PR:
> 
> Screenshot from 2019-11-05 11-04-34
> 
> Current:
> 
> Screenshot from 2019-11-05 11-04-42

Done

**Comment by m52go** [comment]
ACK

**Comment by m52go** [comment]
@gilsanjuan thanks again!

In the future, please try to follow [this style](https://github.com/bisq-network/style/issues/9) for your commit messages. In particular, capitalize first letter and use imperative tense (e.g., "optimized svg images" --> "Optimize svg images").

**Pull request merged**
