### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by huey735**

### CODE REVIEW

**Comment by m52go** [comment]
@huey735 would you mind removing the `outdated_translation` references, since they are part of #220? 

All you have to do is switch to your `addFrTranslations` branch with `git checkout addFrTranslations`, remove all references to `outdated_translation`, commit, and then push. 

Then this PR will automatically reflect the changes -- no need for another PR.

**Comment by huey735** [comment]
@m52go what references? The variables in the front matter? The ones from this PR are not present in https://github.com/bisq-network/bisq-website/pull/220 as French wasn't included in that PR.

**Comment by m52go** [comment]
@huey735 yes, the ones from the front matter. It's ok if they're not in the other PR...we can add them in another PR.

**Comment by m52go** [comment]
ACK

**Pull request merged**
