### PR TITLE
New design

### PR DESCRIPTION
**Pull request by ManfredKarrer**

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
NOT ready to merge yet. Just for testing a preview. Atm. there is a version issue:
```
jekyll-feed-0.11.0 requires ruby version >= 2.3.0, which is incompatible with
the current version, ruby 2.2.9p480
```
@cbeams Would you have time to have a look?

**Comment by cbeams** [comment]
@ManfredKarrer, I'll have a look before our meeting tomorrow.

@m52go, regarding bed069d, the change itself is fine, but I'm not sure we want to link so prominently to the whitepaper on the home page like this. I'd rather the button read 'Get Started' and take the user to https://docs.bisq.network/getting-started.html. The phase zero doc is primarily for a contributor audience. The getting started doc is for users.

The reason the whitepaper link is still so prominent is just historical. It had above-the-fold treatment since the very first design of the website, when referring people to the (original) whitepaper was much more valuable and important. Replacing it with a link to the Getting Started guide better reflects the maturity of the project and its readiness for new users.

**Comment by m52go** [comment]
@cbeams makes a lot of sense, thanks. I didn't originally put that button there but I just made the change.

Overall the site looks ready to me. The blog could use a new post on the new release and some minor stylistic tweaks (e.g., numbered lists look weird), which I can take care of later today.

Otherwise, just 2 minor lingering concerns:

- do we still need the /contribute page? That page has 3 primary sections: contributors, bounties, and donations. We already have a call for contributors on the /community page (although it could be made more prominent), bounties is kind of the same thing, and I'm not sure we're looking for donations right now? Just a thought.
- all download links currently go to bisq-network/exchange. Even though there's a redirect we might want to update to bisq-network/bisq at some point. I didn't change as I wasn't sure if they were still there for another reason.

EDIT: per messages on Slack with Manfred I'll be removing the /contribute page and changing links to bisq-network/bisq.

**Comment by m52go** [comment]
I just removed /contribute and updated GitHub links throughout.

Only thing I'm planning to do now is stylistic updates to /blog later today. I'll hold off on including a new blog post for the release here and instead make a new pull request tomorrow.

**Review by m52go — APPROVED** [review]
From my end, this looks good now.

**Comment by cbeams** [comment]
The version issue described in https://github.com/bisq-network/bisq-website/pull/96#issuecomment-443499619 above is now fixed as of d4e5fa6.

**Comment by cbeams** [comment]
Not sure whether this is a known issue, but there is no trade history available at on teh new integrated /markets page gat https://pedromvpg.github.io/bisq-website/markets/.

The chart is accurate, but the "last 100 trades" list is empty:

image

Note that when I build the site locally, the list is not empty, but rather populated with stale records from Oct 2018.

**Pull request merged**
