### PR TITLE
Implement pedro's getting-started suggestions

### PR DESCRIPTION
**Pull request by m52go**
I've implemented the changes suggested in #372.

Only exception: moving the video selectors below the videos. To me, this seemed to make it harder to find the video selector. @pedromvpg what do you think?

Here's a screenshot of the page after the changes proposed in this PR.

Screenshot_2020-07-28 Getting Started ‹ Bisq - A decentralized bitcoin exchange network

### CODE REVIEW

**Comment by pedromvpg** [comment]
Nice! do you have a netlify link? to test on the browser and mobile?

**Comment by m52go** [comment]
@pedromvpg yup, here: https://deploy-preview-380--bisq-website.netlify.app/getting-started/

**Comment by Bayernatoor** [comment]
This looks really good. Cleaner then the previous version!

I prefer the selection tabs on top, almost acts as a title.

**Comment by pedromvpg** [comment]
Agreed. Much better now IMO

**Comment by m52go** [comment]
Cool! I'll merge soon if there's no further feedback.

**Pull request merged**
