### PR TITLE
update the blog (as discussed in latest issue)

### PR DESCRIPTION
**Pull request by ghost**
I just added 2 lines to the original text.
(We can add more info if we want).

### CODE REVIEW

**Review by cbeams — CHANGES_REQUESTED** [review]
NACK. Please look at the source of other posts and understand Jekyll's "front matter" (the section at the top of the post in between the `---` delimiters.)

Look at the deploy preview of your post compared to other existing posts that have proper front matter:

Yours: https://deploy-preview-67--bisq-website.netlify.com/blog/bisq-v.0.7.1-released/

Another: https://deploy-preview-67--bisq-website.netlify.com/blog/the-bisq-dao-manifesto/

Notice how yours is not styled. Fixing the front matter will fix this. Follow convention with what you see. Read the documentation about front matter at https://jekyllrb.com to really understand what's going on: https://jekyllrb.com/docs/frontmatter/.

Additionally: the blog post as-is has no link to the actual release or downloads page. It is a bit too much of a copy and paste from the release notes in this way.

**Comment by ghost** [comment]
Ok. I take good notice @cbeams. Thanks for the remarks.
I'll correct that tomorrow.

**Comment by cbeams** [comment]
Great. Please also get yourself set up to build and view the site locally by following the instructions at https://github.com/bisq-network/bisq-website#readme. Any time I make a significant change to the site, I always view and test it locally, rather than "flying blind" by just submitting a PR.

**Comment by ghost** [comment]
I signal it here before forgetting and if somebody else encounters the problem:
Under debian 64bits, 
- I had also to install ruby-dev in order for `bundle install `to succeed
- _config.yml must contain `exclude : vendor` in order for `bundle exec jekyll serve` to succeed

... and yes it works :-)

**Comment by ghost** [comment]
So, I modified the front matter and added a link to the download page.
And tested locally.

I would like to add a little something as an introduction, like a quote: 
"It is not because things are difficult that we do not dare, it is because we do not dare that they are difficult." - Lucius Annaeus Seneca 

Too much ? or would be ok.

(I would like to be a bit more verbose, but this would require a bit more time. Next time.)

**Comment by cbeams** [comment]
Ok, @HarryMacfinned. On review, I've changed my mind about this approach. I've pushed two additional commits above that dramatically simplify the announcement post. Here are my notes:

1. This was rapidly becoming an editorial exercise, with all manner of decisions about what should go where, who the author of the post is, whether a quote should be added, a new text at the bottom that needed review by a native English speaker, and more. Our blog is simply not a strategic asset right now. In the last 30 days it's had 750 pageviews. This is 2% of the 36,000 pageviews on the site overall. It is simply not important. The goal of this effort to update the blog was to mitigate whatever negative effect having a stale blog may have on new users getting to know the project. In the process, however, this was becoming a time consuming, subjective exercise that frankly I do not think merits my time, but that I also could not simply click the 'merge' button on because the content has issues and needed further work to be acceptable for publication. For these reasons, the commits I've added dramatically simplify the post down to just a few factual lines. This is a format that can be repeated at every release in a very simple, objective fashion that requires little to no review. Thanks for your efforts, and I hope you understand these motivations for keeping any future such blog posts very simple and easy to repeat.

2. The post title and filename were incorrect. They used the `v.0.7.1` to indicate the version. There is no dot (.) between the `v` and the `0`. This has been fixed.

3. The post was authored by "The Bisq Team". This post was not written by "The Bisq Team". It was written by an individual. There is no "Bisq Team" per se. There are only individual contributors working inside a process toward a common goal. This is an important point vis a vis decentralization and the Bisq DAO, and it is part of the reason I believe we should do away with the blog entirely as part of @pedromvpg's redesign effort (/cc @ripcurlx). I have changed the author to my own name in the meantime, as I am now in fact the person who has written the content. I would have no problem if you wish to change this to your name, but you must actually use your alias appropriately, e.g. "Harry MacFinned". It is preferred that you use two names in this way, but if you prefer "HarryMacFinned" all as one word / one alias name, this is fine too. **If you wish to update the author to your name, please push another commit that does so as soon as possible.** I will plan to merge this PR no later than Monday.

4. Your PR was submitted from your `master` branch. This is to be avoided, because it can easily cause merge hell on your side if your PR is not merged immediately. I will not go into further detail here, but will suffice to say please submit future PRs from a dedicated "topic branch" or sometimes called "feature branch" named e.g. `bisq-v0.7.1`. It is advised that you learn how to make changes and pull requests from the command line or from GitHub Desktop or from a similar client such that you have full control over these matters. The GitHub web interface is limited in the amount of control you have over your PRs.

5. Your email address is obscured by GitHub in your Git commits. Everyone should use proper Git metadata as specified in the https://bisq.network/contributor-checklist.

Again, if you have any comments or wish to change the author name, please get back asap and I'll plan merge this no later than Monday.

**Review by cbeams — APPROVED** [review]

**Comment by ghost** [comment]
Hello @cbeams , I agree with most of your points.
I apologize deeply for the numerous technical worries. I'm doing my best to tame Github ... but it needs some time. Please put the author name you want, I'm not interested in being the author (I'm not !). 
My main worry is to have the blog alive, because I'm absolutely sure (from other experiences) that the blog is one tool in the toolbox for Bisq's growth.
As for the very small % of page read today, this is normal and unavoidable when a blog isn't updated. My experience with many other blogs for many years is that this can change dramatically just by feeding it with fresh news. And I think we have plenty of material for that.
I'll develop about things we could put in the blog later.

Again, great thanks for all your comments.
I'll do my best to catch the right branches next time !

**Comment by ghost** [comment]
Chris, I agree with your straighforward simplification.
(I was rather suprised that you could write in my repo ... ah ah, github surprises me everyday !)
It's indeed better and more effective to have the text about the release in only one main place, and link to it, than to duplicate.
There maybe however a little point:
your text begins with: We recommend all users update immediately.
... but there is no item concerning updating after that.

So I would suggest a first item concerning the updating procedure:

- Update : If you have already Bisq installed, Bisq will detect by itself that an update is available. You just have to follow the (short) procedure. 
- 1st install : Download and install v0.7.1 at <https://bisq.network/downloads>
 - See the complete [release notes](https://github.com/bisq-network/bisq-desktop/releases/tag/v0.7.1) at GitHub
 - Follow the [Getting Started with Bisq](https://docs.bisq.network/getting-started) guide

It's only a suggestion.
If you don't find it useful, please keep to your version.

**Comment by cbeams** [comment]
I've merged the changes as-is, thanks.

**Pull request merged**
