### PR TITLE
Add an overview of the bisq network post

### PR DESCRIPTION
**Pull request by arunasurya**
The text for the draft is final but I may add a visual for the Bisq network. It is ready for the final review.

### CODE REVIEW

**Comment by m52go** [comment]
@arunasurya thanks for making the PR! 

Two things to note:

1. Make sure to begin your post with the following markup, so the site builder knows how to properly integrate your post with the rest of the site:

```
---
layout: post
title: <Title of Your Post>
author: <Your Name>
---
```

As it stands, your post looks like plain text without a header, footer, or styling. Adding the markup above will add those items so it doesn't look like this ([screenshot from here](https://deploy-preview-131--bisq-website.netlify.com/blog/an-overview-of-the-bisq-network/)):

screenshot from 2019-02-25 15-49-27

2. Try not to begin the post with a headline. If you do, the preview on the post listing page has huge text in it ([screenshot from here](https://deploy-preview-131--bisq-website.netlify.com/blog/)):

screenshot from 2019-02-25 15-48-22

**Comment by arunasurya** [comment]
Thanks, @m52go! Will be more careful next time:).

**Comment by ripcurlx** [comment]
@arunasurya Unfortunately the first headline "Introduction" (h2) is still rendered within the teaser on the overview page. Maybe you could start with a general teaser text and start with the introduction afterwards, so all blog posts look similar in the overview page.
bildschirmfoto 2019-02-26 um 14 47 38

**Comment by ripcurlx** [comment]
ACK

**Comment by ripcurlx** [comment]
@arunasurya Do yo want me to merge it right now or do you want to release it later?

**Comment by arunasurya** [comment]
@ripcurlx , we want to add an image to that, so maybe wait till Thursday?

**Comment by arunasurya** [comment]
@ripcurlx, we decided to skip the image, so it is ready to be merged now.

**Pull request merged**
