### PR TITLE
Add stats page

### PR DESCRIPTION
**Pull request by m52go**
To address https://github.com/bisq-network/bisq-website/issues/147.

Notes:

* Added drop-down to navbar to make it less crowded
* Data is hard-coded for the moment, to be updated monthly (with first update right after this upcoming voting cycle is done)
* Bottom blocks need to be centered

Also looks like there are some merge conflicts at the moment (will fix).

But please review for substance.

Preview is broken, so here are screenshots.

Screenshot from 2019-03-29 11-38-43
Screenshot from 2019-03-29 11-39-53

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
Date of downloads is wrong: Released Aug 22nd, 2018
Also downloads number contains all sig files. Would be good to get those filtered out. A small webservice delivering the pure app downloads mighty be nice.

**Comment by ManfredKarrer** [comment]
Not sure if a more graphical approach would be better? @pedromvpg would you have time to make a suggestion?

**Comment by m52go** [comment]
@ManfredKarrer I used 0.9.3 because it had the best numbers...took numbers from here and added up only .dmg .exe .deb numbers:

Screenshot from 2019-03-29 11-42-11

We could use a more recent version but numbers are much lower.

Yes automating these figures will be great, was thinking we could do it all at once, when we automate the Bisq stats.

**Comment by pedromvpg** [comment]
Stats page
https://www.figma.com/proto/D9XHYXcNcobektGe5DpzAhVl/New-Pages?node-id=3%3A1&viewport=-664%2C-169%2C0.357336&scaling=min-zoom

Is this the right list of data to be displayed? If not is there a consolidated list I can reference?

Stats-Desktop

**Comment by m52go** [comment]
That looks good to me. Generally I think we want to include as much as we can from the [analytics infographic](https://bisq.slack.com/archives/C7WRK8DBM/p1551964649007000) and whatever else makes sense (e.g., link to the network monitor).

**Comment by ManfredKarrer** [comment]
@pedromvpg figma crashes often my firefox tabs.... the adobe page was working better

**Comment by ripcurlx** [comment]
I like the design 👍 . Regarding KPIs, graphs and naming I would suggest following:
- Let's name it `Statistics` instead of `Network stats`? It reminds me atm of real network monitoring and not Bisq trading statistics.
- [Graph] Volume
- [KPIs Trading/Client] Total Trades - Daily Average Trades (last month) - Downloads latest (major) release
- [Graph] BSQ Supply
- [Graph] BSQ Burned (by trading)
- [KPIs Community] Github Contributors - Twitter Followers - Slack Users

I think for a first version this information should be sufficient to spark interest.

**Comment by m52go** [comment]
I like @ripcurlx's suggestions...very well thought-out.

Only thing I would mention is that it makes more sense to me to keep BSQ supply and created/burned on the same graph. Maybe the line indicates the net supply over time, and double-bars at each time interval indicate issuance and burning (not sure of the exact graph details; we can figure them out when we actually have the data to make the complete graph).

**Comment by m52go** [comment]
I applied Pedro's design and Christoph's KPIs suggestions. I kept the order of items the same as Pedro's design, as alternating between graphs and KPIs looks a little strange, I think, especially on smaller screens where everything becomes a single column.

Also -- I stuck with v0.9.5 for downloads because v0.9 didn't have too many (which is what I assume ripcurlx meant by major release - 0.8, 0.9, 1.0, etc). I think we just need to play this by ear and use the version that makes most sense.

If there are no further suggestions, this should be ready to go.

Screenshot from 2019-04-12 08-14-17

**Pull request merged**
