### PR TITLE
Prepare website for DAO launch

### PR DESCRIPTION
**Pull request by m52go**
So far, this PR only removes the "coming soon" text on the front page.

TODO:
* change bottom image on dao landing page (@pedromvpg you up for this?)

FAQs and a Stats page will be handled through other PRs.

Please suggest other items you would like to see changed on the website for the DAO launch.

### CODE REVIEW

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Comment by ManfredKarrer** [comment]
@pedromvpg 

Maybe we should add an icon or image to the DAO part on the front page?

Screen Shot 2019-04-05 at 15 51 16

**Comment by pedromvpg** [comment]
Thoughts on this icon?

Desktop-DAO-Icon

**Comment by pedromvpg** [comment]
Here's the file
[DAO.svg.zip](https://github.com/bisq-network/bisq-website/files/3051718/DAO.svg.zip)

**Comment by ManfredKarrer** [comment]
Looks great to me!

**Comment by m52go** [comment]
@pedromvpg this SVG is looking weird. It looks the same when I open it separately. Is the file bad?

Screenshot from 2019-04-10 09-58-46

**Comment by pedromvpg** [comment]
can you try this one?

[dao_graphic.svg.zip](https://github.com/bisq-network/bisq-website/files/3066675/dao_graphic.svg.zip)

**Comment by m52go** [comment]
@pedromvpg that works great, thanks.

**Review by ManfredKarrer — APPROVED** [review]
utACK

**Comment by m52go** [comment]
Not sure how this was left out in the last commit.

This is now ready to go.

**Pull request merged**
