### PR TITLE
Mutil-language,Chinese

### PR DESCRIPTION
**Pull request by kdaye**
# test method
```
git clone -b dev https://github.com/kdaye/bisq.cn.git
cd bisq.cn
vim docker-compose.yml
docker-compose up -d
```

# test run 
sample
https://bisq.cn

# add mutil-language
```
cp _i18n/en _i18n/de
cp _i18n/en.yml _i18n/de.yml
```
add link_de
https://github.com/kdaye/bisq.cn/blob/72bf21a28792f6d2b427e019b39c511a1fc80ad3/_layouts/default.html#L84-L85

### CODE REVIEW

**Comment by ManfredKarrer** [comment]
Ah wow, thanks a lot! @cbeams can you have a look?

**Comment by ManfredKarrer** [comment]
@kdaye We will try to find a dev to work on https://github.com/bisq-network/exchange/issues/971 to add support for pluggable transports. Would you be available for helping with testing?

**Comment by kdaye** [comment]
@ManfredKarrer yep, @ me when it finish.glad to help you.

**Comment by cbeams** [comment]
Hi @kdaye, thank you for putting in so much effort on this already.

Unfortunately, I don't think it makes sense to merge this set of changes right now. The reason is that we plan to radically simplify the website as soon as possible. Many of the existing pages will go away completely, and it's not yet clear what our internationalization needs will be when the new site is complete.

Another reason is that, as Manfred was mentioning above, Bisq basically doesn't work in China right now, and won't until we get Tor pluggable transports worked out. I'm not sure that translating the site into Chinese has much practical value before that's done.

In any case, it would be great to have you do the translations on the new site. At least some of the work you've done here would probably still apply. It's not yet clear when we'll be able to get to redesigning the site, but I'm generally planning on doing it next month (November).

I hope this isn't too big a disappointment, but I think it'll be better to take things one step at a time here. First we'll get the website cleaned up, then we can internationalize it. I've just created #35 to track the redesign, so you might want to subscribe to that.

And feel free to come chat with us in Slack, by the way!

**Comment by kdaye** [comment]
Hi @cbeams ,
That's ok, when I introduce Bisq to Chinese people, they ask the Chinese website, So I made it.

I know Bisq doesn't work in China. and "google.com","coinbase.com","google authenticator" not work in China, but we use VPN/shadowsocks to out of the GFW. to use its services.This is already part of our network life.

Even if they still can not use Bisq, but I think the Chinese page will be like a seed, sooner or later will become a tree. But the question is when you sow the seed.

Anyway，I will keep it alive at bisq.cn. and watch #35 . and chat in slack later. 
Thanks.

**Comment by ManfredKarrer** [comment]
@kdaye  Great! Btw. One dev is now working to get Tor pluggable transports supported for the next release. We also have the app translated to Chinese (see Transifex) in next release. It would still require UI work to adopt layouts with translations as often text is longer and breaks layout, that will take a bit as atm we don't have the dev resource for that.

**Comment by kdaye** [comment]
@ManfredKarrer wow,I can not wait to use the next release. I will make it short if the text breaks the layout.there are different words same means in Chinese.

**Comment by ManfredKarrer** [comment]
@kdaye If you want to have a look to the current app translation, in the development branch it is already added.

screen shot 2017-10-26 at 20 01 44

**Comment by ManfredKarrer** [comment]
@kdaye Could you help testing the Tor pluggable transports we added to our development branch?
See https://github.com/bisq-network/exchange/issues/998
Would be great if we have some people from Mainland China to help testing it.

**Comment by kdaye** [comment]
@ManfredKarrer  OH, I'm sorry, I just returned from my vacation. Has it completed the test? I've tell my friends download the latest version 6.0.

**Comment by ManfredKarrer** [comment]
@kdaye Nobody in China has tested it so far I know. But now its released and hope it helps....

**Comment by kdaye** [comment]
@ManfredKarrer not working for my laptop! all the transport type. Where can I find the log?
I will build Bisq in workstation tomorrow,and report.

**Comment by ManfredKarrer** [comment]
Maybe u need to use custom bridges. The default bridges might be blocked. Log you can open at Account/Backup -> log button

**Pull request closed without merging**
